#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.bin
  $HOME/.local/bin
  $HOME/node_modules/.bin
  $HOME/.local/go/bin
  ${GOPATH}/bin
  $path
)
#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi


### FIXME
#
if [ -e /.dockerinit ] || [ -n "$TMUX" ]; then
  export TERM="screen-256color"
else
  export TERM="xterm-256color"
fi

eval "$(direnv hook zsh)"

local nvm_install_dir
if [ -f "$HOME/.local/opt/nvm/nvm.sh" ]; then
  nvm_install_dir="$HOME/.local/opt/nvm"
else
  nvm_install_dir=$(brew --prefix nvm 2> /dev/null)
  if [ $? != 0 ]; then
    unset nvm_install_dir
  fi
fi

if [[ -n $nvm_install_dir ]]; then
  export NVM_DIR="$HOME/.nvm"
  mkdir -p "$NVM_DIR"
  source "$nvm_install_dir/nvm.sh"
  [ -e "$NVM_DIR/nvm-exec" ] || ln -s "$nvm_install_dir/nvm-exec" "$NVM_DIR/"
fi

# Add all SSH-keys stored in OSX Keychain to the agent
ssh-add -A 2>/dev/null

existing_keys=$(ssh-add -l | awk '{ print "MD5:" $2 }')
# for key in $HOME/.ssh/*.key; do
#   [ -f "$key.pub" ] || ssh-keygen -f "$key" -y > "$key.pub"
#   if ! echo "$existing_keys" | grep -q "$(ssh-keygen -E md5 -l -f "$key.pub" | awk '{ print $2 }')"; then
#     ssh-add "$key" 2>/dev/null
#   fi
# done
