# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 filetype=zsh:

[[ $_zsh_trace ]] && echo ">> zprofile"

if [[ "$OSTYPE" == darwin* ]]; then
	export BROWSER='open'
fi

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

if [[ -z "$LANG" ]]; then
	export LANG='en_US.UTF-8'
fi

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#		$cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
	$HOME/.bin
	$HOME/.local/bin
	$HOME/node_modules/.bin
	$HOME/.local/go/bin
	${GOPATH}/bin
	$path
)

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
	export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

if [ -e /.dockerinit ] || [ -n "$TMUX" ]; then
	export TERM="screen-256color"
else
	export TERM="xterm-256color"
fi

[[ -f $HOME/.profile ]] && source $HOME/.profile

if command -v direnv >/dev/null 2>&1; then
	eval "$(direnv hook zsh)"
fi

export NVM_DIR="${NVM_DIR:-"$HOME/.nvm"}"
if [ -s "$NVM_DIR/nvm.sh" ]; then
	source "$NVM_DIR/nvm.sh"
else
	unset NVM_DIR
fi

# Add all SSH-keys stored in OSX Keychain to the agent
ssh-add -A >/dev/null 2>&1

# existing_keys=$(ssh-add -l | awk '{ print "MD5:" $2 }')
# for key in $HOME/.ssh/*.key; do
#		[ -f "$key.pub" ] || ssh-keygen -f "$key" -y > "$key.pub"
#		if ! echo "$existing_keys" | grep -q "$(ssh-keygen -E md5 -l -f "$key.pub" | awk '{ print $2 }')"; then
#			ssh-add "$key" 2>/dev/null
#		fi
# done
#
[[ $_zsh_trace ]] && echo "<< zprofile"
