#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
[[ $_zsh_trace ]] && echo ">> zshenv"

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

[[ -f "$HOME/.zshenv.local" ]] && source "$HOME/.zshenv.local"

[[ $_zsh_trace ]] && echo "<< zshenv"
